######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 29 20:16:49 2013
######################################################################

QT          *= webkit
CONFIG      *= debug_and_release
TEMPLATE     = app
TARGET       = 
DEPENDPATH  += .
INCLUDEPATH += .
OBJECTS_DIR  = .vitunpaska
MOC_DIR      = .vitunpaska

# Input
HEADERS += websnap.h clock.h perf.h
SOURCES += websnap.cc main.cc clock.cc perf.cc
